# Generated by Django 4.0.5 on 2024-02-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='status',
            field=models.CharField(choices=[('AC', 'Активен'), ('PE', 'Ожидает'), ('EX', 'Истек')], default='AC', max_length=2),
        ),
    ]
